make compatible with fivetran and add readme
fishtown-analytics/bing-ads pull request #7
Opened 2019-03-18 18:27 UTC by eogilvy12

### Fivetran Compatibility 

* add readme
* create fivetran macros
* update models to pull from macros specific to the ETL specified at the project level

I need to confirm that this still works for stitch users - running tests now

2019-03-18 19:13 UTC, jthandy requested changes
small stuff.

2019-03-18 19:13 UTC, jthandy commented on macros/fivetran/base/fivetran_bing_keyword_performance.sql
> +    group by 1, 2, 3, 4, 5, 6, 7
`{{dbt_utils.group_by(7)}}`

2019-03-18 19:13 UTC, jthandy commented on models/base/bing_ad_groups.sql
> +{% endif %}
don't use two separate if/end blocks...use else :) 

`{% elif var('etl') == 'fivetran' %}`

2019-03-18 19:13 UTC, jthandy commented on models/base/bing_ad_groups.sql
> +{% endif %}
same comment for all of the other models as well.

2019-03-19 19:24 UTC, eogilvy12 commented
@jthandy ready for a final look!

2019-03-19 19:53 UTC, jthandy approved these changes

2019-03-19 19:54 UTC, ChrisLawliss approved these changes

2019-03-19 19:59 UTC, merged